# Revolut Growth Analytics - Analysis

Run `python src/etl.py` first so `data/olist.db` exists.

In [1]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

conn = sqlite3.connect('C:/Users/04ama/OneDrive/job-hunt/portfolio-projects/revolut-growth-analytics/data/olist.db')

def run(sql_file):
    with open(sql_file) as f:
        return pd.read_sql_query(f.read(), conn)

In [ ]:
payments_sql =

   customer_state  avg_payment_val  num_orders  avg_payment_instals
0              SP           137.50       43622                 2.62
1              PR           154.15        5262                 2.85
2              ES           154.71        2107                 2.99
3              MG           154.71       12102                 2.98
4              RS           157.18        5668                 2.97
5              RJ           158.53       13527                 2.97
6              DF           161.13        2204                 2.72
7              GO           165.76        2112                 2.95
8              SC           165.98        3754                 2.87
9              BA           170.82        3610                 3.19
10             AM           181.60         154                 3.27
11             MS           186.87         736                 2.91
12             PE           187.99        1728                 3.49
13             MT           195.23         958                 3.05
14             RN           196.78         522                 3.56
15             MA           198.86         767                 3.08
16             CE           199.90        1398                 3.49
17             TO           204.27         301                 2.98
18             PI           207.11         524                 3.44
19             SE           208.44         361                 3.62
20             PA           215.92        1011                 3.20
21             AL           227.08         427                 3.72
22             RO           233.20         261                 3.43
23             PB           248.33         570                 3.76

## Q1: Funnel
Fill in `queries/funnel.sql` first, then run this cell.

In [ ]:
# Q1a: funnel - count of non-null orders per stage, and pct of all orders that reached it

funnel = run('C:/Users/04ama/OneDrive/job-hunt/portfolio-projects/revolut-growth-analytics/queries/funnel.sql')
funnel

# TODO: bar chart of pct_of_total by stage

       stage  orders_reached  pct_of_total
0  purchased           99441        100.00
1   approved           99281         99.84
2    shipped           97658         98.21
3  delivered           96476         97.02

## Finding: ##

In [ ]:

funnel_steps = run(r"C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\revolut-growth-analytics\queries\step_funnel.sql")
funnel_steps

# TODO

  from_stage   to_stage  from_count  to_count  pct_moved_to_next
0    created   approved       99441     99281              99.84
1   approved    shipped       99281     97658              98.37
2    shipped  delivered       97658     96476              98.79

## Finding:##

## Q2: Cohort retention
Fill in `queries/cohort_retention.sql` first, then run this cell.

In [ ]:
cohort_retention = run(r"C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\revolut-growth-analytics\queries\cohort_retention.sql")
cohort_retention

# TODO: pivot to a cohort_month x months_since_first_order grid and plot as a heatmap
# (pandas .pivot_table() + plt.imshow(), or seaborn.heatmap if you install seaborn)

**Finding:**

## Q3: Payment / segment cut
Fill in `queries/payment_by_state.sql` first, then run this cell.

In [67]:

payment = run(r"C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\revolut-growth-analytics\queries\payment_by_state.sql")
payment

# TODO create a bar chart of the top 10 states avg payment value

   customer_state  avg_payment_val  num_orders  avg_payment_instals
0              SP           137.50       43622                  3.0
1              PR           154.15        5262                  3.0
2              ES           154.71        2107                  3.0
3              MG           154.71       12102                  3.0
4              RS           157.18        5668                  3.0
5              RJ           158.53       13527                  3.0
6              DF           161.13        2204                  3.0
7              GO           165.76        2112                  3.0
8              SC           165.98        3754                  3.0
9              BA           170.82        3610                  3.0
10             AM           181.60         154                  3.0
11             MS           186.87         736                  3.0
12             PE           187.99        1728                  3.0
13             MT           195.23         958                  3.0
14             RN           196.78         522                  4.0
15             MA           198.86         767                  3.0
16             CE           199.90        1398                  3.0
17             TO           204.27         301                  3.0
18             PI           207.11         524                  3.0
19             SE           208.44         361                  4.0
20             PA           215.92        1011                  3.0
21             AL           227.08         427                  4.0
22             RO           233.20         261                  3.0
23             PB           248.33         570                  4.0

**Finding:**